FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
COPY microservice-personal/pom.xml microservice-personal/pom.xml
COPY microservice-personal/src microservice-personal/src
RUN mvn clean package -DskipTests -f microservice-personal/pom.xml

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /build/microservice-personal/target/*.jar app.jar
EXPOSE 9002
ENTRYPOINT ["java", "-jar", "app.jar"]