server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedOrigins:
              - "http://localhost:4200"
              - "https://tu-frontend.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: msvc-security
          uri: lb://msvc-security
          predicates:
            - Path=/api/security/**
          filters:
            - PreserveHostHeader

        - id: msvc-personal
          uri: lb://msvc-personal
          predicates:
            - Path=/api/personal/**
          filters:
            - PreserveHostHeader

        - id: msvc-servicio
          uri: lb://msvc-servicio
          predicates:
            - Path=/api/servicio/**
          filters:
            - PreserveHostHeader
eureka:
  instance:
    hostname: ${GATEWAY_HOSTNAME:app-gateway-ariana.azurewebsites.net}
    prefer-ip-address: false
    non-secure-port: 80
    secure-port: 443
  client:
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME:app-eureka-ariana.azurewebsites.net}/eureka/